name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Install node dependencies
      run: npm install
    - name: Compile assets
      run: npm build
    - name: Merge dependencies
      run: |
        mkdir deploy
        mv package.json deploy
        mv node_modules deploy 
    - name: Deploy
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr
        path: deploy
        remote_path: ${{ secrets.DEPLOY_APP_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}